obj-$(CONFIG_DECON_LCD_S6E3HA0K)	+= s6e3ha0k_mipi_lcd.o s6e3ha0k_lcd_ctrl.o
obj-$(CONFIG_DECON_LCD_S6E3HA2K)	+= s6e3ha2k_mipi_lcd.o s6e3ha2k_lcd_ctrl.o
obj-$(CONFIG_DECON_LCD_S6E3FA0)		+= s6e3fa0_mipi_lcd.o s6e3fa0_lcd_ctrl.o

