#
# Makefile for the Cypress touchkey driver
#

obj-$(CONFIG_KEYBOARD_CYPRESS_TOUCH_20075) += cypress-touchkey.o issp_driver_routines.o issp_main.o issp_routines.o
obj-$(CONFIG_KEYBOARD_CYPRESS_TOUCH_MBR31X5) += cypress-touchkey.o cy8cmbr_swd.o SWD_PacketLayer.o SWD_UpperPacketLayer.o
