#
# Makefile for the Broadcom Bridge Driver
#

# Each configuration option enables a list of files.
obj-$(CONFIG_SENSORS_SSP_BBD)		+=	bbd_bridge_c.o bbd_engine.o bbd_packet_layer_c.o transport_layer_c.o
