#
# Makefile for the sensors drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_SENSORS_FINGERPRINT_SYSFS)		+= fingerprint_sysfs.o
obj-$(CONFIG_SENSORS_VFS7XXX)		+= vfs7xxx.o
obj-$(CONFIG_SENSORS_ET310)			+= et310-spi.o et310-spi_data_transfer.o
