#
# Makefile for the vibrator driver ICs with vibrator driver
#

obj-$(CONFIG_MOTOR_DRV_MAX8997)		+= max8997_vibrator.o
obj-$(CONFIG_MOTOR_DRV_MAX77804)	+= max77804_haptic.o
obj-$(CONFIG_MOTOR_DRV_MAX77828)	+= max77828_haptic.o
obj-$(CONFIG_MOTOR_DRV_MAX77833)	+= max77833_haptic.o
obj-$(CONFIG_MOTOR_DRV_MAX77843)	+= max77843_haptic.o
obj-$(CONFIG_MOTOR_DRV_MAX77888)	+= max77888_haptic.o
obj-$(CONFIG_MOTOR_DRV_ISA1200)		+= isa1200_vibrator.o
obj-$(CONFIG_MOTOR_DRV_ISA1400)		+= isa1400_vibrator.o
obj-$(CONFIG_HAPTIC_ISA1200)			+= haptic_isa1200.o
obj-$(CONFIG_HAPTIC_ISA1400)			+= haptic_isa1400.o
obj-$(CONFIG_HAPTIC)				+= haptic.o

obj-$(CONFIG_VIBETONZ)			+= vibrator.o
vibrator-objs				+= tspdrv.o
