# UFSHCD makefile
obj-$(CONFIG_SCSI_UFSHCD) += ufshcd.o ufs_quirks.o
obj-$(CONFIG_SCSI_UFSHCD_PCI) += ufshcd-pci.o
obj-$(CONFIG_SCSI_UFSHCD_PLATFORM) += ufshcd-pltfrm.o
obj-$(CONFIG_SCSI_UFS_EXYNOS) += ufs-exynos.o
obj-$(CONFIG_UFS_FMP_ECRYPT_FS) += fmp_derive_iv.o
obj-$(CONFIG_FIPS_FMP_UFS) += fips-fmp-ufs.o
obj-$(CONFIG_FIPS_FMP_UFS) += first_file.o
obj-$(CONFIG_FIPS_FMP_UFS) += fips-fmp.o fips-fmp-integrity.o
obj-$(CONFIG_FIPS_FMP_UFS) += last_file.o
